app = "passkey-demo-nimble-bliss"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
[env]
  RAILS_ENV = "production"
  MAILER_DEFAULT_HOST = "localhost"
  MAILER_DEFAULT_PORT = "3000"
  MAILER_SENDER = "Test <noreply@nimblehq.co>"
  AVAILABLE_LOCALES = "en"
  DEFAULT_LOCALE = "en"
  FALLBACK_LOCALES = "en"
